# Generated by Django 5.0.6 on 2024-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название записи блога', max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='челевекочитаемая ссылка')),
                ('content', models.TextField(help_text='Введите содержимое блога', verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение блога', null=True, upload_to='blog_image/', verbose_name='превью (изображение)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('publication_sign', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
        ),
    ]
