# Generated by Django 5.0.6 on 2024-05-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
