# Generated by Django 5.0.6 on 2024-05-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='челевекочитаемая ссылка'),
        ),
    ]
